# config/routes.yaml

# the "app_lucky_number" route name is not important yet
main:
    path: /
    controller: App\Controller\MainController::main
prueba:
    path: /lucky-number
    controller: App\Controller\LuckyController::number
prueba-dos:
    path: /test-controller
    controller: App\Controller\TestController::main
